name: Docker Build

on: push

jobs:

  DockerBuild:
    docker-build:
      name: Build docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: main

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build
          run: docker build .